//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Hojaencabezado = new HashSet<Hojaencabezado>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int EmpleadoId { get; set; }
        public string nombres_empleado { get; set; }
        public string apellidos_empleado { get; set; }
        public string direccion_empleado { get; set; }
        public string telefono_empleado { get; set; }
        public string cui_empleado { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public bool estado_empleado { get; set; }
    
        public virtual ICollection<Hojaencabezado> Hojaencabezado { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
