//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;

    public partial class Estadomobiliario
    {
        public Estadomobiliario()
        {
            this.Mobiliario = new HashSet<Mobiliario>();
        }

        public int EstadomobiliarioId { get; set; }
        public string descripcion_estado { get; set; }
        public bool estado_actual { get; set; }

        public virtual ICollection<Mobiliario> Mobiliario { get; set; }
    }

}