//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hojadetalle
    {
        public int HojadetalleId { get; set; }
        public Nullable<int> MobiliarioId { get; set; }
        public Nullable<int> HojaencabezadoId { get; set; }
        public System.DateTime fecha_asignacion { get; set; }
    
        public virtual Mobiliario Mobiliario { get; set; }
        public virtual Hojaencabezado Hojaencabezado { get; set; }
    }
}
