//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;

    public partial class informacion1
    {
        public string nombre_edificio { get; set; }
        public string nombre_ubicacion { get; set; }
        public string nombre_categoria { get; set; }
        public string DescripcionTM { get; set; }
        public string descripcion_mobiliario { get; set; }
    }
}
