//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobiliario
    {
        public Mobiliario()
        {
            this.Hojadetalle = new HashSet<Hojadetalle>();
        }
    
        public int MobiliarioId { get; set; }
        public Nullable<int> EstadomobiliarioId { get; set; }
        public Nullable<int> TipomobiliarioId { get; set; }
        public Nullable<int> UbicacionId { get; set; }
        public string descripcion_mobiliario { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string numero_serie { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public string observacion { get; set; }
    
        public virtual Estadomobiliario Estadomobiliario { get; set; }
        public virtual ICollection<Hojadetalle> Hojadetalle { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        public virtual Tipomobiliario Tipomobiliario { get; set; }
    }
}
