//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int UsuarioId { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public int EmpleadoId { get; set; }
        public int TipousuarioId { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Tipousuario Tipousuario { get; set; }
    }
}
