//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventarioDBEntities : DbContext
    {
        public inventarioDBEntities()
            : base("name=inventarioDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Edificio> Edificio { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Estadomobiliario> Estadomobiliario { get; set; }
        public virtual DbSet<Hojadetalle> Hojadetalle { get; set; }
        public virtual DbSet<Hojaencabezado> Hojaencabezado { get; set; }
        public virtual DbSet<Mobiliario> Mobiliario { get; set; }
        public virtual DbSet<Tipomobiliario> Tipomobiliario { get; set; }
        public virtual DbSet<Ubicacion> Ubicacion { get; set; }
        public virtual DbSet<Tipousuario> Tipousuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
