//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class inventarioDBEntities : DbContext
    {
        public inventarioDBEntities()
            : base("name=inventarioDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categoria> Categoria { get; set; }
        public DbSet<Edificio> Edificio { get; set; }
        public DbSet<Empleado> Empleado { get; set; }
        public DbSet<Estadomobiliario> Estadomobiliario { get; set; }
        public DbSet<Hojadetalle> Hojadetalle { get; set; }
        public DbSet<Hojaencabezado> Hojaencabezado { get; set; }
        public DbSet<Mobiliario> Mobiliario { get; set; }
        public DbSet<Tipomobiliario> Tipomobiliario { get; set; }
        public DbSet<Ubicacion> Ubicacion { get; set; }
        public DbSet<Tipousuario> Tipousuario { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<InformeInventario_Result> InformeInventario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InformeInventario_Result>("InformeInventario");
        }
    }
}
